Repository Icinga/icinga-notifications-web, pull requests merged in 2024-04, with the labels that each got.

#172 php: Split phpstan tests into a separate workflow
  .github/workflows/php.yml
  .github/workflows/phpstan.yml
Labels: cla/signed

#179 Drop incident_history.caused_by_incident_history_id
  library/Notifications/Model/IncidentHistory.php
Labels: cla/signed

#180 js: Don't include scheme and host etc when fetching more results
  public/js/module.js
Labels: bug, cla/signed

#134 Improve longer appointment style
  library/Notifications/Widget/Calendar/BaseGrid.php
  phpstan-baseline-standard.neon
  public/css/calendar.less
Labels: cla/signed, enhancement, area/ui

#152 Provide more intuitive calendar controls
  library/Notifications/Widget/Calendar.php
  library/Notifications/Widget/Calendar/Controls.php
  public/css/calendar.less
Labels: cla/signed, enhancement, area/controls

#155 Fix inefficient list views which render object names
  application/controllers/EventController.php
  application/controllers/EventsController.php
  application/controllers/IncidentController.php
  application/controllers/IncidentsController.php
  library/Notifications/Common/Database.php
  library/Notifications/Model/Behavior/IdTagAggregator.php
  library/Notifications/Model/Event.php
  library/Notifications/Model/Incident.php
  library/Notifications/Model/Objects.php
  library/Notifications/Widget/Detail/IncidentDetail.php
Labels: cla/signed
