Repository Icinga/icinga-notifications-web, pull requests merged in 2024-07, with the labels that each got.

#222 ObjectsRenderer: Add missing `id` column
  library/Notifications/ProvidedHook/Notifications/ObjectsRenderer.php
Labels: bug, cla/signed

#221 Limit contact.username and .contact_address length
  library/Notifications/Web/Form/ContactForm.php
Labels: cla/signed

#223 Support mute, unmute and notification suppression
  library/Notifications/Common/Icons.php
  library/Notifications/Model/Behavior/IdTagAggregator.php
  library/Notifications/Model/Event.php
  library/Notifications/Model/IncidentHistory.php
  library/Notifications/Model/Objects.php
  library/Notifications/Widget/Detail/EventDetail.php
  library/Notifications/Widget/ItemList/EventListItem.php
  library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
  library/Notifications/Widget/ItemList/IncidentListItem.php
  public/css/common.less
  public/css/detail/incident-detail.less
Labels: cla/signed

#229 doc: Mention `status/query` as required permission for Icinga
  doc/03-Configuration.md
Labels: cla/signed

#230 Do not store null for channel options
  application/forms/ChannelForm.php
Labels: cla/signed

#232 Replace functions that are not available in `php72`
  application/forms/EscalationConditionForm.php
  application/forms/EscalationRecipientForm.php
  application/forms/SaveEventRuleForm.php
  library/Notifications/Widget/EventRuleConfig.php
Labels: cla/signed

#236 js: Don't crash UI in case of non-https connections
  public/js/notifications.js
Labels: cla/signed

#237 js: Fix operator precedence issues
  public/js/notifications.js
Labels: cla/signed

#241 Fix hook error handling
  library/Notifications/Hook/ObjectsRendererHook.php
  run.php
Labels: bug, cla/signed

#238 doc: Mention known issues with desktop notifications
  doc/06-Desktop-Notifications.md
Labels: cla/signed, area/documentation

#242 Daemon\Server: Change default listen config
  doc/06-Desktop-Notifications.md
  library/Notifications/Daemon/Server.php
Labels: cla/signed, area/desktop-notifications

#231 ObjectSuggestions: Fix exotic columns match
  library/Notifications/Web/Control/SearchBar/ObjectSuggestions.php
Labels: cla/signed

#243 doc: Mention required apache mods for desktop notifications
  doc/03-Configuration.md
  doc/06-Desktop-Notifications.md
Labels: cla/signed, area/documentation

#245 css: Increase specificity of schedule list rules
  public/css/list/schedule-list.less
Labels: cla/signed

#246 Mention desktop notifications package in docs
  doc/06-Desktop-Notifications.md
Labels: cla/signed, area/documentation

#244 Don't limit browser_session.user_agent to 4096 chars
  library/Notifications/Daemon/Server.php
  library/Notifications/ProvidedHook/SessionStorage.php
Labels: cla/signed

#233 Release v0.1.0
  .mailmap
  AUTHORS
  doc/02-Installation.md.d/From-Source.md
  module.info
Labels: cla/signed
