Repository Icinga/icinga-notifications-web, pull requests merged in 2024-06, with the labels that each got.

#191 ContactController: Fix the retreival of contact full name during deletion
  application/controllers/ContactController.php
Labels: cla/signed

#202 ObjectsRenderer: Use `VolatileStateResults` class for host/service state
  library/Notifications/ProvidedHook/Notifications/ObjectsRenderer.php
Labels: bug, cla/signed

#188 Contactgroup configuration
  application/controllers/ContactGroupController.php
  application/controllers/ContactGroupsController.php
  application/controllers/ContactsController.php
  application/controllers/EventRulesController.php
  application/controllers/SchedulesController.php
  application/forms/ContactGroupForm.php
  configuration.php
  library/Notifications/Common/Links.php
  library/Notifications/Model/Contact.php
  library/Notifications/Model/Contactgroup.php
  library/Notifications/Web/Form/ContactForm.php
  library/Notifications/Widget/ItemList/ContactGroupList.php
  library/Notifications/Widget/ItemList/ContactGroupListItem.php
  library/Notifications/Widget/ItemList/ContactListItem.php
  library/Notifications/Widget/MemberSuggestions.php
  public/css/common.less
Labels: cla/signed, enhancement

#198 ContactForm: Fix saving and populating contact addresses
  library/Notifications/Web/Form/ContactForm.php
  phpstan-baseline-standard.neon
Labels: cla/signed

#183 Schedule redesign
  application/controllers/ScheduleController.php
  application/controllers/SchedulesController.php
  application/forms/EntryForm.php
  application/forms/MoveRotationForm.php
  application/forms/RotationConfigForm.php
  application/forms/ScheduleForm.php
  configuration.php
  library/Notifications/Common/Links.php
  library/Notifications/Model/Contact.php
  library/Notifications/Model/Rotation.php
  library/Notifications/Model/RotationMember.php
  library/Notifications/Model/Schedule.php
  library/Notifications/Model/ScheduleMember.php
  library/Notifications/Model/Timeperiod.php
  library/Notifications/Model/TimeperiodEntry.php
  library/Notifications/Widget/Calendar.php
  library/Notifications/Widget/Calendar/Attendee.php
  library/Notifications/Widget/Calendar/BaseGrid.php
  library/Notifications/Widget/Calendar/DayGrid.php
  library/Notifications/Widget/Calendar/Entry.php
  library/Notifications/Widget/Calendar/MonthGrid.php
  library/Notifications/Widget/Calendar/Util.php
  library/Notifications/Widget/Calendar/WeekGrid.php
  library/Notifications/Widget/Schedule.php
  library/Notifications/Widget/Schedule/Controls.php
  library/Notifications/Widget/TimeGrid/BaseGrid.php
  library/Notifications/Widget/TimeGrid/DynamicGrid.php
  library/Notifications/Widget/TimeGrid/Entry.php
  library/Notifications/Widget/TimeGrid/EntryProvider.php
  library/Notifications/Widget/TimeGrid/ExtraEntryCount.php
  library/Notifications/Widget/TimeGrid/GridStep.php
  library/Notifications/Widget/TimeGrid/Util.php
  library/Notifications/Widget/Timeline.php
  library/Notifications/Widget/Timeline/Entry.php
  library/Notifications/Widget/Timeline/Member.php
  library/Notifications/Widget/Timeline/Rotation.php
  public/css/calendar.less
  public/css/form.less
  public/css/schedule.less
  public/css/timeline.less
  public/img/pictogram/24-7-colored.jpg
  public/img/pictogram/24-7-gray.jpg
  public/img/pictogram/multi-colored.jpg
  public/img/pictogram/multi-gray.jpg
  public/img/pictogram/partial-colored.jpg
  public/img/pictogram/partial-gray.jpg
  public/js/schedule.js
Labels: cla/signed, enhancement, area/view

#205 Contactgroup: Implement missing search-suggestion and search-editor
  application/controllers/ContactGroupsController.php
  library/Notifications/Model/Contactgroup.php
Labels: cla/signed

#203 Contact/Contactgroup: Remove usage of color column
  application/forms/ContactGroupForm.php
  library/Notifications/Model/Contact.php
  library/Notifications/Model/Contactgroup.php
  library/Notifications/Web/Form/ContactForm.php
  library/Notifications/Widget/MemberSuggestions.php
  library/Notifications/Widget/RecipientSuggestions.php
Labels: cla/signed, enhancement

#146 Introduce desktop notifications
  application/clicommands/DaemonCommand.php
  application/controllers/DaemonController.php
  config/systemd/icinga-notifications-web.service
  configuration.php
  doc/06-Desktop-Notifications.md
  library/Notifications/Daemon/Daemon.php
  library/Notifications/Daemon/Sender.php
  library/Notifications/Daemon/Server.php
  library/Notifications/Model/BrowserSession.php
  library/Notifications/Model/Contact.php
  library/Notifications/Model/Daemon/Connection.php
  library/Notifications/Model/Daemon/Event.php
  library/Notifications/Model/Daemon/EventIdentifier.php
  library/Notifications/Model/Daemon/User.php
  library/Notifications/Model/IncidentHistory.php
  library/Notifications/ProvidedHook/SessionStorage.php
  public/img/icinga-notifications-critical.webp
  public/img/icinga-notifications-ok.webp
  public/img/icinga-notifications-unknown.webp
  public/img/icinga-notifications-warning.webp
  public/js/doc/NOTIFICATIONS.md
  public/js/doc/notifications-arch.puml
  public/js/doc/notifications-arch.svg
  public/js/module.js
  public/js/notifications-worker.js
  public/js/notifications.js
  run.php
Labels: cla/signed, enhancement

#216 Support new event types
  library/Notifications/Common/Icons.php
  library/Notifications/Model/Event.php
  library/Notifications/Widget/Detail/EventDetail.php
  library/Notifications/Widget/ItemList/EventListItem.php
Labels: cla/signed, enhancement

#219 ContactGroup: Fix contact deletion
  application/forms/ContactGroupForm.php
Labels: bug, cla/signed, area/configuration
