Repository Icinga/icinga-notifications-web, pull requests merged in 2024-05, with the labels that each got.

#185 IncidentDetail: Use relation `incindent.object` instead of `event.object`
  library/Notifications/Widget/Detail/IncidentDetail.php
  library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
Labels: bug, cla/signed

#186 Move schedule to primary list
  application/controllers/ScheduleController.php
  application/controllers/SchedulesController.php
  application/forms/ScheduleForm.php
  library/Notifications/Common/Links.php
  library/Notifications/Model/Schedule.php
  library/Notifications/Widget/ItemList/ScheduleList.php
  library/Notifications/Widget/ItemList/ScheduleListItem.php
Labels: cla/signed, enhancement

#166 Event and Incident History improvements
  library/Notifications/Common/Icons.php
  library/Notifications/Model/Event.php
  library/Notifications/Model/Incident.php
  library/Notifications/Model/IncidentHistory.php
  library/Notifications/Model/Objects.php
  library/Notifications/Widget/Detail/EventDetail.php
  library/Notifications/Widget/Detail/IncidentDetail.php
  library/Notifications/Widget/Detail/IncidentQuickActions.php
  library/Notifications/Widget/IconBall.php
  library/Notifications/Widget/ItemList/EventListItem.php
  library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
  public/css/common.less
Labels: cla/signed, enhancement, area/view

#181 Move source icon in incident detail to the header
  application/controllers/EventController.php
  application/controllers/IncidentsController.php
  library/Notifications/Widget/Detail/IncidentDetail.php
  library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
  library/Notifications/Widget/ItemList/IncidentListItem.php
  public/css/common.less
Labels: cla/signed, enhancement, area/ui

#175 ChannelForm: Render default values as element values
  application/forms/ChannelForm.php
Labels: cla/signed, enhancement

#127 Add pending notifications incident history messages
  library/Notifications/Model/IncidentHistory.php
  library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
Labels: cla/signed

#189 IncidentsController: Use `severity` as default sort and fix `Opened On`
  application/controllers/IncidentsController.php
Labels: cla/signed

#165 Hook implementation for event object display names
  library/Notifications/Hook/ObjectsRendererHook.php
  library/Notifications/Model/Objects.php
  library/Notifications/Widget/Detail/EventDetail.php
  library/Notifications/Widget/Detail/IncidentDetail.php
  library/Notifications/Widget/ItemList/EventList.php
  library/Notifications/Widget/ItemList/IncidentList.php
  phpstan-baseline-standard.neon
Labels: cla/signed, enhancement

#192 Provide `ObjectsRendererHook` for `icingadb`
  .github/workflows/phpstan.yml
  library/Notifications/ProvidedHook/Notifications/ObjectsRenderer.php
  library/Notifications/Widget/ItemList/EventListItem.php
  library/Notifications/Widget/ItemList/IncidentListItem.php
  phpstan-baseline-standard.neon
  phpstan.neon
  run.php
Labels: cla/signed
