Repository Icinga/icinga-notifications-web, pull requests merged in 2025-04, with the labels that each got.

#312 Ensure compatiblity with Icinga/ipl-web#258
  doc/02-Installation.md.d/From-Source.md
  library/Notifications/Widget/EventSourceBadge.php
  library/Notifications/Widget/ItemList/EventListItem.php
  library/Notifications/Widget/ItemList/IncidentListItem.php
  library/Notifications/Widget/SourceIcon.php
  module.info
  public/css/common.less
Labels: cla/signed

#308 RotationConfigForm: Don't increase priority when editing a rotation
  application/forms/RotationConfigForm.php
Labels: bug, cla/signed

#292 Schedules: Add timescale and time indicator
  library/Notifications/Widget/TimeGrid/Timescale.php
  library/Notifications/Widget/Timeline.php
  public/css/timeline.less
Labels: cla/signed

#318 RotationConfigForm: Fix incorrect thumbnail descriptions and example
  application/forms/RotationConfigForm.php
  public/css/form.less
Labels: bug, cla/signed

#319 Timeline: Add title to `drag-handle` of the rotation title and fix css
  library/Notifications/Widget/Timeline.php
  public/css/timeline.less
Labels: cla/signed

#317 RotationConfigForm: Don't increase priority when editing a rotation
  application/forms/RotationConfigForm.php
Labels: cla/signed

#324 Use 'addElement()' to add CSRF tokens and UID elements
  application/forms/AddEscalationForm.php
  application/forms/AddFilterForm.php
  application/forms/BaseEscalationForm.php
  application/forms/EventRuleForm.php
  application/forms/RemoveEscalationForm.php
Labels: cla/signed

#325 Handle unicode in contact and contact group names
  library/Notifications/Widget/ItemList/ContactGroupListItem.php
  library/Notifications/Widget/ItemList/ContactListItem.php
Labels: cla/signed, area/representation

#328 Force line-break for days-header
  public/css/timeline.less
Labels: cla/signed

#311 Ensure new/updated rows having a changed_at greater than all previous ones
  application/forms/ChannelForm.php
  application/forms/ScheduleForm.php
  application/forms/SourceForm.php
  library/Notifications/Common/Database.php
Labels: cla/signed

#323 ObjectsRendererHook: Always use `_next` as `data-base-target`
  library/Notifications/Hook/ObjectsRendererHook.php
Labels: bug, cla/signed
